name: Random Task Runner

on:
  schedule:
    # This schedules the job to run every day at 3 PM, 4 PM, and 5 PM.
    - cron: '0 15,16,17 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install setuptools
      run: pip install setuptools

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install blinker

    - name: Upgrade Selenium
      run: pip install selenium --upgrade

    - name: Conditional random wait time
      if: ${{ github.event_name == 'schedule' }}
      # Random wait time between 0 to 7200 seconds (0 to 2 hours)
      run: sleep $(( RANDOM % 7200 ))

    - name: Run the main script
      run: python main.py
      # Alternatively, if you want to use the auto-update script, replace the above line with:
      # run: python autoupdate_main.py
